### ISSUE TITLE
noEther modifier

### ISSUE THREAD

**Issue by ethers** [ConsenSys/Tokens#22]
// Prevents methods from perfoming any value transfer
        modifier noEther() {if (msg.value > 0) throw; _}

Should we add this to all the methods?

**Comment by simondlr** [comment]
I suspect for HumanStandardToken implementation, it would be useful, since there's no way to resend the eth out in there. However, for StandardToken, it could changed/implemented for functions to include eth.

eg, if you want to transfer tokens you have to send a special tx fee of an additional 1 eth.

but, yes. Would be useful to add in the HumanStandardToken.sol

**Comment by ethers** [comment]
No longer needed since `payable` is required by Solidity.
